[project]
name = "knack-sleuth"
version = "0.1.19"
description = "Investigate your Knack.app's metadata to find where data objects and fields are used throughout your application"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx[http2]>=0.28.1",
    "pydantic>=2.12.3",
    "pydantic-settings>=2.11.0",
    "pyyaml>=6.0.3",
    "typer>=0.20.0",
]

[project.scripts]
knack-sleuth = "knack_sleuth.cli:cli"

[build-system]
requires = ["uv_build>=0.9.5,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "bump-my-version>=1.2.4",
    "pytest>=8.4.2",
    "pytest-mock>=3.15.1",
]


[tool.bumpversion]
current_version = "0.1.19"
commit = true
tag = true

[[tool.bumpversion.files]]
filename = "pyproject.toml"
search = 'version = "{current_version}"'
replace = 'version = "{new_version}"'

[[tool.bumpversion.files]]
filename = "src/knack_sleuth/__init__.py"
search = '__version__ = "{current_version}"'
replace = '__version__ = "{new_version}"'


[project.urls]
Homepage = "https://github.com/mcmasty/knack-sleuth"
Repository = "https://github.com/mcmasty/knack-sleuth"
Issues = "https://github.com/mcmasty/knack-sleuth/issues"

[tool.pytest.ini_options]
minversion = "8.0"
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = [
    "-ra",
    "--strict-markers",
    "--strict-config",
]
